name: Test 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test: 
    runs-on: windows-latest
    steps:
      - name: Debug via SSH
        uses: luchihoratiu/debug-via-ssh@v1.1